name: TangledMazePlus
version: ${project.version}
main: me.gorgeousone.tangledmaze.TangledMazePlugin
api-version: 1.13

commands:
    tangledmaze:
        aliases: [maze, tm]

permissions:
    tangledmaze.build:
        default: op
    tangledmaze.reload:
        default: op
    tangledmaze.tp:
        default: op
    tangledmaze.backup:
        default: op